# If we configure the azure.activedirectory.client-id or azure.activedirectory.app-id-uri will be to check the audience.
# In v2.0 tokens, this is always the client ID of the API, while in v1.0 tokens it can be the client ID or the resource URI used in the request.
# If you are using v1.0 tokens, configure both to properly complete the audience validation.

server:
  port: 8083

azure:
  activedirectory:
    #tenant-id: 779811d8-4753-4c34-baeb-6b53957d52e3
    client-id: a3bc9b43-9309-473f-b4f5-cf2a5879baa7
    app-id-uri: api://a3bc9b43-9309-473f-b4f5-cf2a5879baa7 

